### ISSUE TITLE
Two spaces proof

### ISSUE THREAD

**Issue by zg** [mdo/code-guide#102]
Where is the proof of this statement? https://github.com/mdo/code-guide/blob/gh-pages/index.html#L68-L69

**Comment by mdo** [comment]
I don't mean to sound dick-ish or arrogant, it's simply matter of fact. If you use tabs, someone's dev environment might have 8-space tabs and you 4-space. With _soft tabs_, the same spaces in one piece of code can be copy-pasted to another person's computer and will render the exact same because a space is a space. One person's tab doesn't always equal another person's tab.

**Comment by josh18** [comment]
Out of curiosity is there any particular reason that you use 2 spaces instead of 4? For me personally I find it harder to see indentations when they are only 2 spaces long but it could just be what I am used to.

**Comment by zg** [comment]
You can fit more onto the screen, and you also save space by having two spaces instead of four.

**Comment by Ganginator** [comment]
I disagree.

It is more readable to use hard indents, and then mnify your code for
production.

Human readability is more important during development, and simple
minification like Grunt solves any specific issues for production.

Ganginator

_Jesse Gangi_
jessegangi.com
(218) 310-2447
jgangi@aerialapps.com
@Ganginator https://twitter.com/Ganginator

**Comment by zg** [comment]
Why don't you prefer the number of spaces I prefer!?

**Comment by josh18** [comment]
Sorry, didn't mean to start a war, was just wondering if there is any major benefit or logical reasoning behind using 2 spaces instead of 4. IMO the benefits that @zg mentioned are very minimal compared to the decrease in legibility that it causes (for me anyways).

**Comment by Ganginator** [comment]
I understand that everyone has their preference.
And I have much respect for you all, so I must state that there is no
negativity.

However, I do choose to do hard tabs in development for readability, and
then choose to minify in production after for performance.

Ganginator

_Jesse Gangi_
jessegangi.com
(218) 310-2447
jgangi@aerialapps.com
@Ganginator https://twitter.com/Ganginator

**Comment by pixelastic** [comment]
I don't think there is any particular reason to have 2 spaces instead of 4. Use what suits you (and your team) best. The goal of any style guide is to have a commonly agreed set of rules. Same goes for tabs. The important thing here is that all code in the project must look like it has been written by the same person.

**Comment by zg** [comment]
This issue was closed, and hasn't been reopened, so clearly he's going with two spaces.

**Comment by josh18** [comment]
I'm not debating that it should be anything else I am just asking what the reasoning was (if any) behind using 2 spaces instead of 4. He explained above why he chose spaces over tabs but he didn't really say why he chose 2 spaces over 4 spaces.

**Comment by zg** [comment]
https://github.com/mdo/code-guide/issues/102#issuecomment-46631618

**Comment by josh18** [comment]
^ ?

**Comment by mdo** [comment]
Two spaces feels less of a waste of space and makes small chunks of code feel more related to each other. I'm just super used to it at this point—the number of spaces doesn't matter as much, so long as they are spaces.

**Comment by josh18** [comment]
@mdo thanks for your input. I'm a fairly new coder and am just trying to make sure I don't adopt bad habits that are much harder to break later on.

**Comment by bbertucc** [comment]
@mdo - Could your syntax tab rules be simplified to "Use soft tabs—they're the only way to guarantee code renders the same in any environment." ?? The reason for "two" also confounded me when I started learning your standards. Most other style choices seem to have a practical reason beyond your initial feeling.

**Comment by Alhadis** [comment]
Use tabs to indent, and spaces to align. Make sure the two don't touch. Simple.

That way, anybody can use whatever indentation size they want without breaking column alignment. Also, I can't stand reading code indented with 2-space soft-tabs. It drives me _CRAZY_.
