### ISSUE TITLE
Suggestion Bootstrap Expo

### ISSUE THREAD

**Issue by ThePokyWizard** [mdo/code-guide#116]
The site is: www.tomticket.com

**Comment by mehmetdik** [comment]
Thanks

**Comment by mdo** [comment]
Wrong repo.

**Comment by mehmetdik** [comment]
I did not understand what you want

**Comment by ThePokyWizard** [comment]
Just wrong repository.

Flávio Tomazio
www.tomticket.com | www.twitter.com/flaviotomazio

2014-10-21 17:06 GMT-02:00 Mehmet Dik notifications@github.com:
