### ISSUE TITLE
⌥ Option key doesn't show up right

### ISSUE THREAD

**Issue by akaleeroy** [mdo/code-guide#119]
Nitpicking here... on the [Prefixed properties section](http://codeguide.co/#css-prefixed-properties) the [⌥](http://www.fileformat.info/info/unicode/char/2325/index.htm) `U+2325` key isn't showing up right in my browser (Chrome 39 on Windows 7). At least I think you meant Option, I'm seeing a box with an x, and if I copy the character it's [⌃](http://www.fileformat.info/info/unicode/char/2303/index.htm) `U+2303`.

**Comment by diagramatics** [comment]
Just for test outcome variations, I'm using Chrome 41 in Windows 8.1 and it shows ⌃ correctly.
