### ISSUE TITLE
Add mention of media query preferences

### ISSUE THREAD

**Issue by adamwintle** [mdo/code-guide#13]
What's the best way to include and structure media queries in a CSS file?

Should they all be bundled together at the end of the style sheet? Each media query next to the related classes? Other technique?

**Comment by mdo** [comment]
Hah, great timing—gave a talk on last Thursday that asked this very question. Short answer is in each component's file (this is how we have it thus far in Bootstrap 3).

**Comment by mdo** [comment]
Got it coming in my update. Holy shit late I know <3.
