### ISSUE TITLE
Swap aria-*, role in Attribute order section

### ISSUE THREAD

**Issue by ghost** [mdo/code-guide#148]
`role` should be defined first, followed by an `aria-*` property since a lot of ARIA roles expect certain properties to be used in conjunction with.

For example,

``` html
<span role="checkbox" aria-checked="true"></span>
```

makes perfect sense, rather than to have the attributes the other way around.

**Comment by mdo** [comment]
I dig that. Want to open a PR? :)

**Comment by indrekpaas** [comment]
Cheers, will do and closing this ticket.
