### ISSUE TITLE
Any kind of linter? Conformance tester ..?

### ISSUE THREAD

**Issue by fabm22** [mdo/code-guide#155]
Hi 

I'd like to know if there 's any kind of linter or conformance tester of this particular style guide ? I know of bootlint for bootstrap etc. but those are aimed at bootstrap. Is there other linters of the preferences and advices formulated in this code-guide ? Thanks

**Comment by mdo** [comment]
Nothing for this one that I'm aware of, sorry.

**Comment by kwickramasekara** [comment]
Checking back on this issue to see if there has been any development in this. Specially interested in linters that would handle HTML attribute order.
