### ISSUE TITLE
Site Suggestion

### ISSUE THREAD

**Issue by marekhrabe** [mdo/code-guide#161]
Christmas themed website about gifts for designers: 
https://xmas.mockuuups.com/ (and also [gift detail page](https://xmas.mockuuups.com/gift-for/friends-of-bootstrap/?code=edgfgnmiwhaq8kg0b17r5zisf))

**Comment by mdo** [comment]
Guessing this was opened in the wrong repo and you meant this for the Bootstrap Expo :). Feel free to repost it there if so.

**Comment by marekhrabe** [comment]
Thank you, I just reposted there :)
