### ISSUE TITLE
Omit <html> <head> and <body> tags

### ISSUE THREAD

**Issue by techtonik** [mdo/code-guide#162]
Speccy says that these tags are not useful anymore.

https://google.github.io/styleguide/htmlcssguide.xml#Optional_Tags

**Comment by mdo** [comment]
I'll pass on recommending that just yet—I understand the benefits, but for a handful of bytes, it doesn't seem all that beneficial in the grand scheme.

**Comment by techtonik** [comment]
Yes. I was surprised to see that. Break a turing-complete XML-head inside of me. =)
