### ISSUE TITLE
Combining media queries

### ISSUE THREAD

**Issue by stramel** [mdo/code-guide#164]
I agree that it is nice to have the media queries "as close to their relevant rule sets whenever possible". This generates a bunch of extra code that can't be minimized by just compilation or minification. Thoughts on mentioning a tool like [node-combine-mq](https://github.com/frontendfriends/node-combine-mq) to combine them into matching media queries? This would compliment the notion of having them close to their relevance while also the benefits of combining them.

**Comment by mdo** [comment]
Going to steer clear of anything like that for now. Performance wise, the number of media queries doesn't matter much from what I've heard. Gzipping will also help reduce file size there by essentially de-duping repeated strings, like media queries.
