### ISSUE TITLE
Setting the charset meta will reduce the Google Page Speed Insights and Yahoo Slow test results

### ISSUE THREAD

**Issue by eugeneford** [mdo/code-guide#165]
Setting the charset meta will reduce the Google Page Speed Insights and Yahoo Slow test results. I hope, you will remove this rule from you guideline.

**Comment by mdo** [comment]
Source or other stats to back that up?

**Comment by eugeneford** [comment]
@mdo, seems like its not actual now: https://gtmetrix.com/reports/eugeneford.info/18CupHZY
