### ISSUE TITLE
CSS declaration order - complete list missing

### ISSUE THREAD

**Issue by kevinkucharczyk** [mdo/code-guide#169]
https://github.com/mdo/code-guide/blob/69974273b9d9095e53aa39cc7d0cd1c0a93bf23d/index.html#L249

Recess is no longer maintained and no full, ordered list of properties is available. It would be great to include such a list or update the link.

**Comment by stramel** [comment]
Closest thing to "full" ATM AFAIK. https://github.com/twitter/recess/blob/master/lib/lint/strict-property-order.js

**Comment by kevinkucharczyk** [comment]
@stramel that looks pretty good, thanks! Still, it would be nice to maybe link directly to this file in the code guide (or have it available in the guide, maybe in some kind of popover or modal).

**Comment by joemaller** [comment]
The Recess link should be removed since the project is EOL. 

Would CSSComb be a suitable replacement? That project includes several default configs with different takes on property sort order: https://github.com/csscomb/csscomb.js/tree/master/config

**Comment by alexweissman** [comment]
From @stramel's link, it appears that the complete list would be:

## Positioning
- position
- top
- right
- bottom
- left
- z-index

## Box Model
- display
- float
- width
- height
- max-width
- max-height
- min-width
- min-height
- padding
- padding-top
- padding-right
- padding-bottom
- padding-left
- margin
- margin-top
- margin-right
- margin-bottom
- margin-left
- margin-collapse
- margin-top-collapse
- margin-right-collapse
- margin-bottom-collapse
- margin-left-collapse
- overflow
- overflow-x
- overflow-y
- clip
- clear

## Typography
- font
- font-family
- font-size
- font-smoothing
- osx-font-smoothing
- font-style
- font-weight
- hyphens
- src
- line-height
- letter-spacing
- word-spacing
- color
- text-align
- text-decoration
- text-indent
- text-overflow
- text-rendering
- text-size-adjust
- text-shadow
- text-transform
- word-break
- word-wrap
- white-space
- vertical-align
- list-style
- list-style-type
- list-style-position
- list-style-image

## Visual
- pointer-events
- cursor
- background
- background-attachment
- background-color
- background-image
- background-position
- background-repeat
- background-size
- border
- border-collapse
- border-top
- border-right
- border-bottom
- border-left
- border-color
- border-image
- border-top-color
- border-right-color
- border-bottom-color
- border-left-color
- border-spacing
- border-style
- border-top-style
- border-right-style
- border-bottom-style
- border-left-style
- border-width
- border-top-width
- border-right-width
- border-bottom-width
- border-left-width
- border-radius
- border-top-right-radius
- border-bottom-right-radius
- border-bottom-left-radius
- border-top-left-radius
- border-radius-topright
- border-radius-bottomright
- border-radius-bottomleft
- border-radius-topleft
- content
- quotes
- outline
- outline-offset

## Miscellaneous
- opacity
- filter
- visibility
- size
- zoom
- transform
- box-align
- box-flex
- box-orient
- box-pack
- box-shadow
- box-sizing
- table-layout
- animation
- animation-delay
- animation-duration
- animation-iteration-count
- animation-name
- animation-play-state
- animation-timing-function
- animation-fill-mode
- transition
- transition-delay
- transition-duration
- transition-property
- transition-timing-function
- background-clip
- backface-visibility
- resize
- appearance
- user-select
- interpolation-mode
- direction
- marks
- page
- set-link-source
- unicode-bidi
- speak

Does this look accurate?

**Comment by ivanaugustobd** [comment]
CSS is always getting new properties, so this list will always be outdated (like `grid` in this year). Would not it be more interesting to use alphabetical order?

**Comment by Deele** [comment]
@alexweissman I updated the list

## Positioning

- position
- top
- right
- bottom
- left
- z-index

## Box Model

- display
- float
- width
- height
- max-width
- max-height
- min-width
- min-height
- padding
- padding-top
- padding-right
- padding-bottom
- padding-left
- margin
- margin-top
- margin-right
- margin-bottom
- margin-left
- margin-collapse
- margin-top-collapse
- margin-right-collapse
- margin-bottom-collapse
- margin-left-collapse
- overflow
- overflow-x
- overflow-y
- clip
- clear
- align-content
- align-items
- align-self
- flex
- flex-basis
- flex-direction
- flex-flow
- flex-grow
- flex-shrink
- flex-wrap
- order
- justify-content
- box-decoration-break
- nav-down
- nav-index
- nav-left
- nav-right
- nav-up

## Typography

- font
- font-family
- font-size
- font-smoothing
- font-size-adjust
- font-stretch
- osx-font-smoothing
- font-style
- font-weight
- font-variant
- hyphens
- src
- line-height
- letter-spacing
- word-spacing
- color
- text-align
- text-align-last
- text-decoration
- text-emphasis
- text-emphasis-color
- text-emphasis-position
- text-emphasis-style
- text-indent
- text-overflow
- text-overflow-ellipsis
- text-overflow-mode
- text-rendering
- text-size-adjust
- text-shadow
- text-transform
- text-justify
- text-outline
- text-wrap
- word-break
- word-wrap
- white-space
- vertical-align
- list-style
- list-style-type
- list-style-position
- list-style-image
- counter-increment
- counter-reset

## Visual

- pointer-events
- cursor
- background
- background-attachment
- background-color
- background-image
- background-position
- background-position-x
- background-position-y
- background-repeat
- background-size
- background-origin
- border
- border-collapse
- border-top
- border-right
- border-bottom
- border-left
- border-color
- border-image
- border-image-outset
- border-image-repeat
- border-image-slice
- border-image-source
- border-image-width
- border-top-color
- border-right-color
- border-bottom-color
- border-left-color
- border-spacing
- border-style
- border-top-style
- border-right-style
- border-bottom-style
- border-left-style
- border-width
- border-top-width
- border-right-width
- border-bottom-width
- border-left-width
- border-radius
- border-top-right-radius
- border-bottom-right-radius
- border-bottom-left-radius
- border-top-left-radius
- border-radius-topright
- border-radius-bottomright
- border-radius-bottomleft
- border-radius-topleft
- content
- quotes
- outline
- outline-offset
- outline-color
- outline-style
- outline-width

## Miscellaneous

- opacity
- filter
- visibility
- size
- zoom
- transform
- transform-origin
- box-align
- box-flex
- box-orient
- box-pack
- box-shadow
- box-sizing
- table-layout
- caption-side
- empty-cells
- animation
- animation-delay
- animation-direction
- animation-duration
- animation-iteration-count
- animation-name
- animation-play-state
- animation-timing-function
- animation-fill-mode
- transition
- transition-delay
- transition-duration
- transition-property
- transition-timing-function
- background-clip
- backface-visibility
- resize
- appearance
- user-select
- interpolation-mode
- direction
- marks
- page
- set-link-source
- unicode-bidi
- speak
- tab-size

PHPStorm originally used

```
font, font-family, font-size, font-weight, font-style, font-variant, font-size-adjust, font-stretch, line-height, position, z-index, top, right, bottom, left, display, visibility, float, clear, overflow, overflow-x, overflow-y, clip, zoom, align-content, align-items, align-self, flex, flex-flow, flex-basis, flex-direction, flex-grow, flex-shrink, flex-wrap, justify-content, order, box-sizing, width, min-width, max-width, height, min-height, max-height, margin, margin-top, margin-right, margin-bottom, margin-left, padding, padding-top, padding-right, padding-bottom, padding-left, table-layout, empty-cells, caption-side, border-spacing, border-collapse, list-style, list-style-position, list-style-type, list-style-image, content, quotes, counter-reset, counter-increment, resize, cursor, user-select, nav-index, nav-up, nav-right, nav-down, nav-left, transition, transition-delay, transition-timing-function, transition-duration, transition-property, transform, transform-origin, animation, animation-name, animation-duration, animation-play-state, animation-timing-function, animation-delay, animation-iteration-count, animation-direction, text-align, text-align-last, vertical-align, white-space, text-decoration, text-emphasis, text-emphasis-color, text-emphasis-style, text-emphasis-position, text-indent, text-justify, letter-spacing, word-spacing, text-outline, text-transform, text-wrap, text-overflow, text-overflow-ellipsis, text-overflow-mode, word-wrap, word-break, tab-size, hyphens, pointer-events, opacity, color, border, border-width, border-style, border-color, border-top, border-top-width, border-top-style, border-top-color, border-right, border-right-width, border-right-style, border-right-color, border-bottom, border-bottom-width, border-bottom-style, border-bottom-color, border-left, border-left-width, border-left-style, border-left-color, border-radius, border-top-left-radius, border-top-right-radius, border-bottom-right-radius, border-bottom-left-radius, border-image, border-image-source, border-image-slice, border-image-width, border-image-outset, border-image-repeat, outline, outline-width, outline-style, outline-color, outline-offset, background, background-color, background-image, background-repeat, background-attachment, background-position, background-position-x, background-position-y, background-clip, background-origin, background-size, box-decoration-break, box-shadow, text-shadow
```

My list:

```
position, top, right, bottom, left, z-index, display, float, width, height, max-width, max-height, min-width, min-height, padding, padding-top, padding-right, padding-bottom, padding-left, margin, margin-top, margin-right, margin-bottom, margin-left, margin-collapse, margin-top-collapse, margin-right-collapse, margin-bottom-collapse, margin-left-collapse, overflow, overflow-x, overflow-y, clip, clear, align-content, align-items, align-self, flex, flex-basis, flex-direction, flex-flow, flex-grow, flex-shrink, flex-wrap, order, justify-content, box-decoration-break, nav-down, nav-index, nav-left, nav-right, nav-up, font, font-family, font-size, font-smoothing, font-size-adjust, font-stretch, osx-font-smoothing, font-style, font-weight, font-variant, hyphens, src, line-height, letter-spacing, word-spacing, color, text-align, text-align-last, text-decoration, text-emphasis, text-emphasis-color, text-emphasis-position, text-emphasis-style, text-indent, text-overflow, text-overflow-ellipsis, text-overflow-mode, text-rendering, text-size-adjust, text-shadow, text-transform, text-justify, text-outline, text-wrap, word-break, word-wrap, white-space, vertical-align, list-style, list-style-type, list-style-position, list-style-image, counter-increment, counter-reset, pointer-events, cursor, background, background-attachment, background-color, background-image, background-position, background-position-x, background-position-y, background-repeat, background-size, background-origin, border, border-collapse, border-top, border-right, border-bottom, border-left, border-color, border-image, border-image-outset, border-image-repeat, border-image-slice, border-image-source, border-image-width, border-top-color, border-right-color, border-bottom-color, border-left-color, border-spacing, border-style, border-top-style, border-right-style, border-bottom-style, border-left-style, border-width, border-top-width, border-right-width, border-bottom-width, border-left-width, border-radius, border-top-right-radius, border-bottom-right-radius, border-bottom-left-radius, border-top-left-radius, border-radius-topright, border-radius-bottomright, border-radius-bottomleft, border-radius-topleft, content, quotes, outline, outline-offset, outline-color, outline-style, outline-width, opacity, filter, visibility, size, zoom, transform, transform-origin, box-align, box-flex, box-orient, box-pack, box-shadow, box-sizing, table-layout, caption-side, empty-cells, animation, animation-delay, animation-direction, animation-duration, animation-iteration-count, animation-name, animation-play-state, animation-timing-function, animation-fill-mode, transition, transition-delay, transition-duration, transition-property, transition-timing-function, background-clip, backface-visibility, resize, appearance, user-select, interpolation-mode, direction, marks, page, set-link-source, unicode-bidi, speak, tab-size
```

**Comment by mdo** [comment]
A full and up to date list is now linked.
