### ISSUE TITLE
Javascript code guide

### ISSUE THREAD

**Issue by a-ivanov81** [mdo/code-guide#17]
Bootstrap have very pretty javascript code. What code guide and rules you use? In contributions of bootstrap I found only that:
- No semicolons
- Comma first
- 2 spaces (no tabs)
- strict mode
- "Attractive"

Thanks

**Comment by ghost** [comment]
I've just been having this conversation tonight too with a team. Best I could find was http://javascript.crockford.com/code.html

Love this Repo and standards.

**Comment by mdo** [comment]
Since I don't write JS, I'm going to pass on this for now.
