### ISSUE TITLE
Italian translation Error

### ISSUE THREAD

**Issue by ghost** [mdo/code-guide#184]
**#css-media-queries**

From
> Proprietà con prefissi

> Quando usi proprietà con prefissi specifici, indenta ogni proprietà in modo che il valore della dichiarazione sia allineato **verticlamente**, per facilitare la modifica multilinea.

To
> Proprietà con prefissi

> Quando usi proprietà con prefissi specifici, indenta ogni proprietà in modo che il valore della dichiarazione sia allineato **verticalmente**, per facilitare la modifica multilinea.

**Comment by mdo** [comment]
I don't maintain the translations.
