### ISSUE TITLE
编码规范 by @mdo

### ISSUE THREAD

**Issue by RedForc** [mdo/code-guide#190]
语法 
"不要在自闭合（self-closing）元素的尾部添加斜线 -- HTML5 规范中明确说明这是可选的。" --这一条是不对的，没有闭合标签，很多浏览器识别不了,造成页面错版。兼容性特别的差，非常难处理。

属性顺序
id, name  应该是第一位的。按照重要程度来的, 如果定义了Id，说明js中会用到这个元素。id放在第一位能够快速的查找元素.class反而不是那么重要,一般页面调好了cssClass一般不会变。

**Comment by mark-job** [comment]
HTML 属性应当按照以下给出的顺序依次排列，确保代码的易读性。

class
id, name
data-*
src, for, type, href, value
title, alt
role, aria-*
class 用于标识高度可复用组件，因此应该排在首位。id 用于标识具体组件，应当谨慎使用（例如，页面内的书签），因此排在第二位。
