### ISSUE TITLE
Grouping & ordering Bootstrap classes

### ISSUE THREAD

**Issue by KatieMFritz** [mdo/code-guide#197]
Thanks for creating this styleguide! I'm working on a design system, and having these rules will keep it clean and consistent.

You've specified an [order of attributes](http://codeguide.co/#html-attribute-order) for HTML and a [declaration order](http://codeguide.co/#css-declaration-order) for CSS , but I can't find a recommended order for classes, here or elsewhere on the net. 

I'm trying to use Bootstrap classes wherever possible, instead of writing my own CSS, and it's getting unwieldy in some places. For example:

```html
<div class="container navbar navbar-light bg-light navbar-expand-md flex-wrap align-items-start">
  <div class="collapse navbar-collapse justify-content-end flex-wrap order-5" id="navbarNav">
```

Obviously, we can't make rules for every single class! But I'm curious: **do you have any guidelines for grouping and ordering layout/component/utility classes, especially within Bootstrap 4?**

**Comment by mdo** [comment]
This is outside the scope of a generic guide—Bootstrap specific requirements should come from Bootstrap.
