### ISSUE TITLE
Multiple translations not exist

### ISSUE THREAD

**Issue by BenjaminHoegh** [mdo/code-guide#204]
Multiple translations don't exist

 - Danish
 - Dutch
 - Czech
 - italian

**Comment by BenjaminHoegh** [comment]
Have created a [Danish version](https://benjaminhoegh.github.io/code-guide/) but I'm not a professional translator so there may be errors. I would try to fix all errors over times but if any person sees one they are welcome to write back and I would change it

**Comment by mdo** [comment]
Checked them and cleared out 404s. Thanks!
