### ISSUE TITLE
HTTPS

### ISSUE THREAD

**Issue by coliff** [mdo/code-guide#210]
Now that GitHub Pages supports custom domains with SSL it'd be good to see this site use HTTPS.
REF: https://blog.github.com/2018-05-01-github-pages-custom-domains-https/

**Comment by coliff** [comment]
Site is on HTTPS now. Nice one MDO. :-)
https://codeguide.co/

**Comment by mdo** [comment]
Woo, thanks! Had to update the DNS and then it's just a checkbox in repo settings :D.
