### ISSUE TITLE
Advice on JavaScript generated markup offers no solution

### ISSUE THREAD

**Issue by vanillajonathan** [mdo/code-guide#213]
The section "JavaScript generated markup" simple states "Writing markup in a JavaScript file makes the content harder to find, harder to edit, and less performant. Avoid it whenever possible.".

It tells you what not to do.
But it offers no solution or advice on alternatives.

Perhaps the [`template`](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/template) element is a viable alternative?

**Comment by tsejx** [comment]
你发给我的邮件已经收到了～辛苦了～
