### ISSUE TITLE
What about css grid?

### ISSUE THREAD

**Issue by roket1428** [mdo/code-guide#232]
There's nothing about css grid in twbs/stylelint-config-twbs-bootstrap.

**Comment by mdo** [comment]
I'd suggest opening an issue in that repo and not here. For property order, it fits somewhere in the box model area. I'll leave this open as a reminder to at least give it a mention here.

**Comment by roket1428** [comment]
> I'd suggest opening an issue in that repo and not here. For property order, it fits somewhere in the box model area. I'll leave this open as a reminder to at least give it a mention here.

I opened an issue and suggest a list of order but still waiting an answer (I opened an issue before this).
