### ISSUE TITLE
add webComponent specific attribute to Attribute Order

### ISSUE THREAD

**Issue by rbalet** [mdo/code-guide#239]
I think the following should be added to the `Attribute Order` since webcomponent are more and more used.  (I'm working with angular, but would make sense for any other framework)
```html
    <custom-component
      [type]="myType"
      [ngSwitch]="condition"
      (myEvent)="onMyEvent()"
      *ngIf="enabled"
    ></custom-component>
```
_I would put those after the `data-*` one (`'data-.+', 'ng-.+', '[.+', '(.+', '*ng+',`)_

**Comment by mdo** [comment]
Closing as duplicate-ish of #259.

**Comment by rbalet** [comment]
> Closing as duplicate-ish of #239.

@mdo 
May have you put the wrong duplicate link '^^

**Comment by mdo** [comment]
Updated! Sorry :)
