### ISSUE TITLE
Suggestion: Adding Sticky “Back to Top” Button

### ISSUE THREAD

**Issue by NH-0** [mdo/code-guide#291]
Hello, 

I would like to suggest the addition of a sticky "Back to Top" button. This button would remain visible as users scroll down the page, allowing them to easily navigate back to the top without the need for excessive scrolling. 

Thank you for considering this suggestion!

**Comment by beMySun** [comment]
Hello!  Your E-mail has been recieved and I will respond you as soon as possible.Best wishes!

**Comment by mdo** [comment]
Thanks but I'll pass.
