### ISSUE TITLE
font/ → fonts/

### ISSUE THREAD

**Issue by zlatanvasovic** [mdo/code-guide#32]
Could you rename the `font/` to `fonts/` as it's better name for directories with more than one file?

**Comment by mdo** [comment]
Technically it's one font, so I'll leave it as-is. Thanks though!

**Comment by zlatanvasovic** [comment]
Okay, but don't forget to change the name if you add a new font.

2014-03-03 9:17 GMT+01:00 Mark Otto notifications@github.com:

> Technically it's one font, so I'll leave it as-is. Thanks though!
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/mdo/code-guide/issues/32#issuecomment-36489065
> .

## 

Zlatan Vasović - _ZDroid_

**Comment by mdo** [comment]
Yup! <3
