### ISSUE TITLE
Charset

### ISSUE THREAD

**Issue by zlatanvasovic** [mdo/code-guide#52]
Code guide recommends `<meta charset="UTF-8">`, but more common way is `<meta charset="utf-8">` (I don't know do they differ).

What way should be used?

**Comment by Smedzlatko** [comment]
w3.org document (http://www.w3.org/TR/html-markup/meta.charset.html) states this:

A case-insensitive match for any character set name for which the IANA [Character Sets] registry has a Name or Alias field labeled as “preferred MIME name”; or, if none of the Alias fields are so labeled, a case-insensitive match for a Name field in the registry.

**Comment by mdo** [comment]
Either way seems fine. As @Smedzlatko I think you'll only run into trouble with an XML page (like XHTML), per the linked spec:

> For documents in the XML syntax, the value of the charset attribute must be a case-insensitive match for the string "UTF-8".

So, given we're HTML, and UTF is an abbreviation, we'll leave it as capitalized I guess.

**Comment by zlatanvasovic** [comment]
@mdo I asked you about that because Bootstrap is using that way. :P 

So, given we're HTML, and we write tags, attributes and the most of attribute values in the lower case, why shouldn't we write `utf-8`?

We are not writing this:

``` html
<META CHARSET="UTF-8">
```

:wink:

**Comment by mdo** [comment]
True, but when referencing it, it's UTF, not utf. I'll leave it as-is in the guide, but folks can do whatever they like. I don't care much either way for that kind of thing.

**Comment by zlatanvasovic** [comment]
Okay.
