### ISSUE TITLE
UX - scroll page by clicking on right/left parts on the window

### ISSUE THREAD

**Issue by techtonik** [mdo/code-guide#55]
It is convenient to list image galleries when you just click on image right and left to get forth and back. It would be a good usability feature for the guide as well.

**Comment by mdo** [comment]
I don't think that's something we need to document here. That said, we should have some usability/accessibility info.

**Comment by techtonik** [comment]
It is not a documentation proposal.

**Comment by mdo** [comment]
Then what were you suggesting?

**Comment by techtonik** [comment]
I am suggesting a change to the behavior of http://mdo.github.io/code-guide/ site to use page left and right margins as a clickable pagination areas.

**Comment by mdo** [comment]
Ah, word. I'll pass on that since I don't want to maintain it :laughing:.

**Comment by techtonik** [comment]
So you don't know if that's possible.

**Comment by mdo** [comment]
If I understand you correctly, it's possible—I just don't want to do it.

**Comment by techtonik** [comment]
Nevermind. I thought you're some kind of web guru. =)

**Comment by hnrch02** [comment]
Saying no to some things doesn't mean he isn't a guru—sometimes it it precisely that what makes great "gurus" :wink:

**Comment by techtonik** [comment]
I mean that for a guru in my world implementing such usability thing is a no-brainer.

**Comment by mdo** [comment]
There's no usability advantage in adding clicks to scroll the page. Just scroll, yo.

**Comment by techtonik** [comment]
Ok. I guess we need UX guru for this issue. =)

**Comment by hnrch02** [comment]
I don't think we need anybody for this issue, @mdo doesn't like the idea so it's not gonna happen.

**Comment by techtonik** [comment]
I am not an UX guru to argue with you. I am just a user.
