### ISSUE TITLE
recommend using @charset in CSS files?

### ISSUE THREAD

**Issue by cvrebert** [mdo/code-guide#58]
e.g. `@charset "UTF-8";`
So that the file's encoding is explicit and will override misconfigured servers.

**Comment by amitburst** [comment]
I think this is only really useful if you're using non-ASCII characters in your CSS (in a `content` property, for example). Even if the server is misconfigured and doesn't specify the charset in the `Content-type` part of HTTP headers, browsers will fallback to _assuming_ your document is `UTF-8`. This is a good reference for anyone interested: https://developer.mozilla.org/en-US/docs/Web/CSS/@charset

**Comment by mdo** [comment]
Yeah, I don't normally ever set this and I've never run into any issues.

**Comment by mdo** [comment]
Noodled on it, passing for now. Folks, let me know if you run into this more often than not and I'll revisit.
