### ISSUE TITLE
Add lang attribute to html tag as recommendation

### ISSUE THREAD

**Issue by guerrero** [mdo/code-guide#59]
From [html tag section](http://www.w3.org/html/wg/drafts/html/master/semantics.html#the-html-element) in W3C HTML5 Editor's draft:

> Authors are encouraged to specify a lang attribute on the root html element, giving the document's language. This aids speech synthesis tools to determine what pronunciations to use, translation tools to determine what rules to use, and so forth.

So IMHO would be nice to have a recommendation to use `lang` attribute into `<html>` tag.

**Comment by amitburst** [comment]
I agree, I think it would be useful to include this recommendation. It can be important for displaying the best quality glyphs for some languages too. http://www.w3.org/TR/html401/struct/dirlang.html#adef-lang

**Comment by mdo** [comment]
Legit.
