### ISSUE TITLE
SASS/LESS variable names

### ISSUE THREAD

**Issue by equivalentideas** [mdo/code-guide#63]
Interested to know if the same thinking as the class name recommendation applies to SASS/LESS variable names.

Recommendations for variable names would be very helpful for people writing css through a preprocessor, but who don't have knowledge of programming language style recommendations.

Great project :+1:

**Comment by uixmat** [comment]
I was thinking the same thing earlier, I've always done my best to limit variable names to two words with camelCase. That's my personal preference. If the variable can be limited semantically to just one word the all lowercase is my top choice!

**Comment by diagramatics** [comment]
Seeing how Bootstrap's LESS variables are named, I suppose the standards are using hyphens as separators — like how you write classes.
