### ISSUE TITLE
Classes over generic element tags

### ISSUE THREAD

**Issue by alrick** [mdo/code-guide#7]
In the guide, it's said `Use classes over generic element tags`
What's the reason of this? I mean, that's only convention or it's "technically" better to use classes over generic elements tags?

Thanks for your answer.

**Comment by mdo** [comment]
Performance—browsers read selectors from right to left, finding matching dom elements and narrowing the results as it reads the selector. There will be fewer classes, and should thus perform better.

**Comment by alrick** [comment]
Thanks :)
