### ISSUE TITLE
double vs single quotes

### ISSUE THREAD

**Issue by aleemb** [mdo/code-guide#73]
What is the motivation for single vs double quotes?

It is often desirable to switch between the two as per convenience. For example in PHP it is better to write (1) `echo "<a href='$href'>";` as opposed to (2) `"echo <a href=\"$href\">";`.

HTML and for that matter most other languages allow for single versus double quotes for this reason.

**Comment by ritcheyer** [comment]
Why couldn't you simply solve this in your PHP using single quotes?

```
echo '<a href="$href">';
```

**Comment by aleemb** [comment]
PHP doesn't allow variables inside single quotes and treats them as literals.

```
 $href = "foo";
 echo '<a href="$href">'; // outputs <a href="$href">
 echo "<a href='$href'>"; // outputs <a href='foo'>
```

This is a very common idiom in PHP.

**Comment by mdo** [comment]
This is an HTML and CSS code guide, so it doesn't take any other programming language into account for the most part. That sounds like a pretty shitty limitation on PHP's part though :laughing:.

**Comment by ritcheyer** [comment]
:+1: haha
