### ISSUE TITLE
Leading zero

### ISSUE THREAD

**Issue by zlatanvasovic** [mdo/code-guide#77]
> Don't include spaces after commas within `rgb()`, `rgba()`, `hsl()`, `hsla()`, or `rect()` values. This helps differentiate multiple color values (comma, no space) from multiple property values (comma with space). **Also, don't prefix values with a leading zero (e.g., `.5` instead of `0.5`).**

Okay, it's for `rgba(0,0,0,.5)`, but is it for other units?

Example: `margin: -.5em` and `margin: .5em`

Is my example good code or bad?

**Comment by mdo** [comment]
Prefixing applies to all values. Should probably break it out to emphasize that.

**Comment by zlatanvasovic** [comment]
Yeah I was thinking about something like that. Only problem is that `-.5em` looks a bit _weird_.
