### ISSUE TITLE
有关于一个注释的标注的错误

### ISSUE THREAD

**Issue by angrilove** [mdo/code-guide#88]
如下图标示，self-closing是自闭的标注，请放置到“和”字之前
![语法标注错误](https://cloud.githubusercontent.com/assets/5861092/2587329/d5f98c02-ba1b-11e3-81e5-e1abd5c17019.png)

**Comment by mdo** [comment]
Sorry, I don't know what you're referring to. Is this on the official version of the guide, or a translation? If the latter, please open an issue with them.
