### ISSUE TITLE
Missing favicon on GH pages

### ISSUE THREAD

**Issue by drublic** [mdo/code-guide#9]
The favicon is referenced in the HTML as follows

```
<link href="/public/ico/favicon.ico" rel="shortcut icon" type="image/x-icon">
```

The folder `ico` doesn't exist in `public` and thus no favicon is present.

**Comment by mdo** [comment]
Going to rewrite all that after I push this big update, so I'll tackle this with that. <3

**Comment by pickfire** [comment]
@mdo, Is it fixed now? It seems like the following lines produces `404 Error`:

``` html
<link href="public/ico/favicon.ico" rel="shortcut icon" type="image/x-icon">
```
